doctrine:
    dbal:
   # DATABASE_URL 'mysql://db_user:.mypwd@mysql8-service:3306/my_db?serverVersion=8.0'
        url: '%env(resolve:DATABASE_URL)%'
        driver:   pdo_mysql
        host:     mysql8-service:3306
        dbname:   my_db
        user:     db_user
        password: .mypwd

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '8.0'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
